<a href="https://colab.research.google.com/github/MalekNaimi/VGGish-Model/blob/master/Tunisiancode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive 
drive.mount('/content/drive',force_remount=True) 

Mounted at /content/drive


In [ ]:
!git clone https://github.com/MalekNaimi/VGGish-Model

Cloning into 'VGGish-Model'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 145 (delta 92), reused 29 (delta 9), pack-reused 0
Receiving objects: 100% (145/145), 116.75 KiB | 9.73 MiB/s, done.
Resolving deltas: 100% (92/92), done.


In [ ]:
!pip3 install numpy
!pip3 install resampy
%tensorflow_version 1.x
!pip3 install tf_slim
!pip3 install six
!pip3 install soundfile

TensorFlow 1.x selected.
     |████████████████████████████████| 358kB 8.1MB/s 


In [ ]:
%cd '/content/VGGish-Model/non-overlap'

/content/VGGish-Model/non-overlap


In [ ]:
!python generate_test_train_data.py

A1, #sum files: 43
A2, #sum files: 134
A3, #sum files: 260
A4, #sum files: 332
A5, #sum files: 403
A6, #sum files: 447
A7, #sum files: 478
A8, #sum files: 553
A9, #sum files: 603
A10, #sum files: 687
A11, #sum files: 718
A12, #sum files: 802
A13, #sum files: 867
A14, #sum files: 874
A15, #sum files: 1088
A16, #sum files: 1122
A17, #sum files: 1179
A18, #sum files: 1237
A19, #sum files: 1309
A20, #sum files: 1357
A21, #sum files: 1394
A22, #sum files: 1499
A23, #sum files: 1543
A24, #sum files: 1586
A25, #sum files: 1615
A26, #sum files: 1616
A27, #sum files: 1714
A28, #sum files: 1761
A29, #sum files: 1806
A30, #sum files: 1830
A31, #sum files: 1838
A32, #sum files: 1872
A33, #sum files: 1896
A34, #sum files: 1945
A35, #sum files: 2024
A36, #sum files: 2072
A37, #sum files: 2082
A38, #sum files: 2136
A39, #sum files: 2141
A40, #sum files: 2143
A41, #sum files: 2152
A42, #sum files: 2158
A43, #sum files: 2195
A44, #sum files: 2238
A45, #sum files: 2284
A46, #sum files: 2291
A47, #sum fi

In [ ]:
!python model_train.py

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



Instructions for updating:
Please use `layer.__call__` method instead.
Instructions for updating:
Use keras.layers.flatten instead.

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where




2021-07-07 12:33:51.559630: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-07-07 12:33:51.634560: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-07 12:33:51.635131: I tensorflow/c

In [ ]:
!python evaluate_acc.py

100% 118/118 [00:00<00:00, 21873.33it/s]
frame_accuracy: 0.5328467153284672
absolute_clip_accuracy: 0.3644067796610169
standard_clip_accuracy: 0.5169491525423728
average_logits_clip_accuracy: 0.5169491525423728
[[21.000 3.000 2.000 2.000]
 [7.000 2.000 7.000 5.000]
 [2.000 3.000 21.000 5.000]
 [10.000 2.000 9.000 17.000]]


In [ ]:
%cd '/content/VGGish-Model/overlap'

/content/VGGish-Model/overlap


Units =200

In [ ]:
!python generate_test_train_data.py

A1, #sum files: 43
A2, #sum files: 134
A3, #sum files: 260
A4, #sum files: 332
A5, #sum files: 403
A6, #sum files: 447
A7, #sum files: 478
A8, #sum files: 553
A9, #sum files: 603
A10, #sum files: 687
A11, #sum files: 718
A12, #sum files: 802
A13, #sum files: 867
A14, #sum files: 874
A15, #sum files: 1088
A16, #sum files: 1122
A17, #sum files: 1179
A18, #sum files: 1237
A19, #sum files: 1309
A20, #sum files: 1357
A21, #sum files: 1394
A22, #sum files: 1499
A23, #sum files: 1543
A24, #sum files: 1586
A25, #sum files: 1615
A26, #sum files: 1616
A27, #sum files: 1714
A28, #sum files: 1761
A29, #sum files: 1806
A30, #sum files: 1830
A31, #sum files: 1838
A32, #sum files: 1872
A33, #sum files: 1896
A34, #sum files: 1945
A35, #sum files: 2024
A36, #sum files: 2072
A37, #sum files: 2082
A38, #sum files: 2136
A39, #sum files: 2141
A40, #sum files: 2143
A41, #sum files: 2152
A42, #sum files: 2158
A43, #sum files: 2195
A44, #sum files: 2238
A45, #sum files: 2284
A46, #sum files: 2291
A47, #sum fi

In [ ]:
!python overlap_train.py

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



Instructions for updating:
Please use `layer.__call__` method instead.
Instructions for updating:
Use keras.layers.flatten instead.

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where




2021-07-07 13:57:14.659466: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-07-07 13:57:14.726592: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-07 13:57:14.727165: I tensorflow/c

In [ ]:
!python evaluate_acc.py

100% 175/175 [00:00<00:00, 19637.31it/s]
frame_accuracy: 0.5661290322580645
absolute_clip_accuracy: 0.41714285714285715
standard_clip_accuracy: 0.5714285714285714
average_logits_clip_accuracy: 0.5942857142857143
[[29.000 5.000 3.000 2.000]
 [4.000 14.000 9.000 8.000]
 [6.000 7.000 34.000 4.000]
 [12.000 3.000 12.000 23.000]]
